url: "https://cnli.info"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
  #     css_class: 'highlight'
  #     span:
  #       line_numbers: false
  #     block:
  #       line_numbers: true

paginate: 15
permalink: /:title

# For RSS xml
title: Earth's moon
description: － Survive Technically －
url: https://cnli.info/
feed: /rss.xml
author_info: <a href="https://cnli.info/">Earth's moon</a>

# Author info. Please update them accordingly.
author: 
  name: Earth's moon
  email: mulescifi@gmail.com
  link: https://cnli.info/
  github: https://github.com/Liecn
  # instagram: https://instagram.com/lantern_d
  # facebook: https://www.facebook.com/yangdavid1028
  # twitter: https://twitter.com/Lantern_D
  # linkedin: https://www.linkedin.com/in/deliang-yang-649a9380/
  # youtube: https://www.youtube.com/channel/UCPAJ2XwlkmbCvVZ-asjfi3w
  # flickr: https://www.flickr.com/photos/lanternd
  telegram: https://telegram.me/ChenningLi

# Image host prefix
# img-hosting: https://img-cdn.dlyang.me

# Gavatar and favicon
gavatar: /img/favicon-96x96.png
favicon: /img/favicon.ico

# Google analytics
ga:
  id: G-C2LWMR3RJD
  url: https://cnli.info/
  userid: 154795237

# Disqus ID
disqus:
  shortname: MuleScifi

# # LiveRe ID
# livere:
#   uid: MTAyMC8yODcxNi81Mjg3

# Jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - rouge

# For sitemap.txt
production_url: https://cnli.info
